version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./Backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./Frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=blockmetric
      - MYSQL_USER=blockmetric
      - MYSQL_PASSWORD=blockmetric
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Backend/src/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  mysql_data: